package com.kang.model;

// Generated 2013-11-27 14:50:48 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TReimitm generated by hbm2java
 */
@Entity
@Table(name = "t_reimitm", catalog = "spring3hibernate4")
public class TReimitm implements java.io.Serializable {

	private Integer rmitmid;
	private TReim TReim;
	private String rmitmname;
	private BigDecimal rmitmcost;
	private String rmitmdesc;

	public TReimitm() {
	}

	public TReimitm(TReim TReim, String rmitmname, BigDecimal rmitmcost,
			String rmitmdesc) {
		this.TReim = TReim;
		this.rmitmname = rmitmname;
		this.rmitmcost = rmitmcost;
		this.rmitmdesc = rmitmdesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rmitmid", unique = true, nullable = false)
	public Integer getRmitmid() {
		return this.rmitmid;
	}

	public void setRmitmid(Integer rmitmid) {
		this.rmitmid = rmitmid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rmid")
	public TReim getTReim() {
		return this.TReim;
	}

	public void setTReim(TReim TReim) {
		this.TReim = TReim;
	}

	@Column(name = "rmitmname", length = 50)
	public String getRmitmname() {
		return this.rmitmname;
	}

	public void setRmitmname(String rmitmname) {
		this.rmitmname = rmitmname;
	}

	@Column(name = "rmitmcost", precision = 12)
	public BigDecimal getRmitmcost() {
		return this.rmitmcost;
	}

	public void setRmitmcost(BigDecimal rmitmcost) {
		this.rmitmcost = rmitmcost;
	}

	@Column(name = "rmitmdesc", length = 100)
	public String getRmitmdesc() {
		return this.rmitmdesc;
	}

	public void setRmitmdesc(String rmitmdesc) {
		this.rmitmdesc = rmitmdesc;
	}

}
