package com.kang.model;

// Generated 2013-11-27 14:50:48 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UsrRoleLink generated by hbm2java
 */
@Entity
@Table(name = "usr_role_link", catalog = "spring3hibernate4")
public class UsrRoleLink implements java.io.Serializable {

	private Integer linkId;
	private Integer usrid;
	private Integer roleid;

	public UsrRoleLink() {
	}

	public UsrRoleLink(Integer usrid, Integer roleid) {
		this.usrid = usrid;
		this.roleid = roleid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "linkId", unique = true, nullable = false)
	public Integer getLinkId() {
		return this.linkId;
	}

	public void setLinkId(Integer linkId) {
		this.linkId = linkId;
	}

	@Column(name = "usrid")
	public Integer getUsrid() {
		return this.usrid;
	}

	public void setUsrid(Integer usrid) {
		this.usrid = usrid;
	}

	@Column(name = "roleid")
	public Integer getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

}
