
DROP TABLE IF EXISTS messages ;
DROP TABLE IF EXISTS payrecords ;
DROP TABLE IF EXISTS bills ;
DROP TABLE IF EXISTS users ;


CREATE TABLE `users` (
  `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `AGE` VARCHAR(45) NOT NULL,
  `BALANCE` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB;

CREATE TABLE `messages` (
  `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `USER_ID` INTEGER UNSIGNED NOT NULL,
  `CONTENT` TEXT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_MESSAGE_USER_ID` FOREIGN KEY `FK_USER_ID` (`USER_ID`)
    REFERENCES `users` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
)
ENGINE = InnoDB;

CREATE TABLE `bills` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INTEGER UNSIGNED NOT NULL,
  `fees` DOUBLE NOT NULL,
  `paid_fees` DOUBLE NOT NULL,
  `unpaid_fees` DOUBLE NOT NULL,
  `pay_status` INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_BILL_USERS_ID` FOREIGN KEY `FK_USERS_ID` (`user_id`)
    REFERENCES `users` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
)
ENGINE = InnoDB;

CREATE TABLE `payrecords` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `bill_id` INTEGER UNSIGNED NOT NULL,
  `paid_fees` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_PAY_RECORD_BILLS_ID` FOREIGN KEY `FK_BILLS_ID` (`bill_id`)
    REFERENCES `bills` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
)
ENGINE = InnoDB;

INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('1','U1',21,80);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('2','U2',22,90);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('3','U3',19,70);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('4','U4',25,60);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('5','U5',27,60);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('6','U6',30,90);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('7','U7',21,90);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('8','U8',23,100);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('9','U9',30,70);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('10','U10',28,80);

INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('11','U11',21,80);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('12','U12',22,90);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('13','U13',19,70);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('14','U14',25,60);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('15','U15',27,60);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('16','U16',30,90);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('17','U17',21,90);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('18','U18',23,100);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('19','U19',30,70);
INSERT INTO USERS(ID,NAME,AGE,BALANCE) VALUES('20','U20',28,80);
COMMIT;