package com.mavenHiberate4.model;

// Generated 2013-11-27 14:50:48 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysRoles generated by hbm2java
 */
@Entity
@Table(name = "sys_roles", catalog = "spring3hibernate4")
public class SysRoles implements java.io.Serializable {

	private Integer roleId;
	private String roleName;
	private String roleUrl;

	public SysRoles() {
	}

	public SysRoles(String roleName, String roleUrl) {
		this.roleName = roleName;
		this.roleUrl = roleUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "roleId", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "roleName", length = 40)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "roleUrl", length = 100)
	public String getRoleUrl() {
		return this.roleUrl;
	}

	public void setRoleUrl(String roleUrl) {
		this.roleUrl = roleUrl;
	}

}
